/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		JoinMeetingForm: typeof import(
			"./src/components/JoinMeetingForm.vue",
		)["default"];
		LucideAlertCircle: typeof import("~icons/lucide/alert-circle")["default"];
		LucideCopy: typeof import("~icons/lucide/copy")["default"];
		LucideMic: typeof import("~icons/lucide/mic")["default"];
		LucideMicOff: typeof import("~icons/lucide/mic-off")["default"];
		LucideMonitorPause: typeof import("~icons/lucide/monitor-pause")["default"];
		LucideMonitorUp: typeof import("~icons/lucide/monitor-up")["default"];
		LucidePhoneOff: typeof import("~icons/lucide/phone-off")["default"];
		LucidePlus: typeof import("~icons/lucide/plus")["default"];
		LucideVideo: typeof import("~icons/lucide/video")["default"];
		LucideVideoOff: typeof import("~icons/lucide/video-off")["default"];
		MeetingAvatar: typeof import(
			"./src/components/MeetingAvatar.vue",
		)["default"];
		MeetingPreview: typeof import(
			"./src/components/MeetingPreview.vue",
		)["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		SFUDashboard: typeof import("./src/components/SFUDashboard.vue")["default"];
		VideoPreview: typeof import("./src/components/VideoPreview.vue")["default"];
	}
}
