/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module "vue" {
	export interface GlobalComponents {
		AudioIndicator: typeof import(
			"./src/components/AudioIndicator.vue",
		)["default"];
		ChatNotification: typeof import(
			"./src/components/ChatNotification.vue",
		)["default"];
		ChatNotificationQueue: typeof import(
			"./src/components/ChatNotificationQueue.vue",
		)["default"];
		ChatPanel: typeof import("./src/components/ChatPanel.vue")["default"];
		ClickToCopyField: typeof import(
			"./src/components/ClickToCopyField.vue",
		)["default"];
		DeviceSettingsDialog: typeof import(
			"./src/components/DeviceSettingsDialog.vue",
		)["default"];
		FloatingControls: typeof import(
			"./src/components/FloatingControls.vue",
		)["default"];
		GroupTile: typeof import("./src/components/GroupTile.vue")["default"];
		JoinRequestNotifications: typeof import(
			"./src/components/JoinRequestNotifications.vue",
		)["default"];
		LucideAlertCircle: typeof import("~icons/lucide/alert-circle")["default"];
		LucideArrowLeft: typeof import("~icons/lucide/arrow-left")["default"];
		LucideCamera: typeof import("~icons/lucide/camera")["default"];
		LucideCheck: typeof import("~icons/lucide/check")["default"];
		LucideClock: typeof import("~icons/lucide/clock")["default"];
		LucideCopy: typeof import("~icons/lucide/copy")["default"];
		LucideInfo: typeof import("~icons/lucide/info")["default"];
		LucideMessageSquare: typeof import(
			"~icons/lucide/message-square",
		)["default"];
		LucideMessageSquareDot: typeof import(
			"~icons/lucide/message-square-dot",
		)["default"];
		LucideMessageSquareOff: typeof import(
			"~icons/lucide/message-square-off",
		)["default"];
		LucideMic: typeof import("~icons/lucide/mic")["default"];
		LucideMicOff: typeof import("~icons/lucide/mic-off")["default"];
		LucideMonitorPause: typeof import("~icons/lucide/monitor-pause")["default"];
		LucideMonitorUp: typeof import("~icons/lucide/monitor-up")["default"];
		LucideMoreHorizontal: typeof import(
			"~icons/lucide/more-horizontal",
		)["default"];
		LucidePhoneOff: typeof import("~icons/lucide/phone-off")["default"];
		LucidePlus: typeof import("~icons/lucide/plus")["default"];
		LucideRefreshCw: typeof import("~icons/lucide/refresh-cw")["default"];
		LucideSettings: typeof import("~icons/lucide/settings")["default"];
		LucideSpeaker: typeof import("~icons/lucide/speaker")["default"];
		LucideUsers: typeof import("~icons/lucide/users")["default"];
		LucideVideo: typeof import("~icons/lucide/video")["default"];
		LucideVideoOff: typeof import("~icons/lucide/video-off")["default"];
		LucideVolume2: typeof import("~icons/lucide/volume2")["default"];
		LucideVolumeX: typeof import("~icons/lucide/volume-x")["default"];
		LucideX: typeof import("~icons/lucide/x")["default"];
		LucideXCircle: typeof import("~icons/lucide/x-circle")["default"];
		MeetingAvatar: typeof import(
			"./src/components/MeetingAvatar.vue",
		)["default"];
		MeetingInfoDialog: typeof import(
			"./src/components/MeetingInfoDialog.vue",
		)["default"];
		MeetingPreview: typeof import(
			"./src/components/MeetingPreview.vue",
		)["default"];
		NamePill: typeof import("./src/components/NamePill.vue")["default"];
		ParticipantTile: typeof import(
			"./src/components/ParticipantTile.vue",
		)["default"];
		RouterLink: typeof import("vue-router")["RouterLink"];
		RouterView: typeof import("vue-router")["RouterView"];
		ScreenShareLayout: typeof import(
			"./src/components/ScreenShareLayout.vue",
		)["default"];
		ScreenShareSidebar: typeof import(
			"./src/components/ScreenShareSidebar.vue",
		)["default"];
		SFUDashboard: typeof import("./src/components/SFUDashboard.vue")["default"];
		VideoGrid: typeof import("./src/components/VideoGrid.vue")["default"];
		VideoPreview: typeof import("./src/components/VideoPreview.vue")["default"];
	}
}
