exclude: "node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: "meet.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff
        name: "Run ruff import sorter"
        args: ["--select=I", "--fix"]

      - id: ruff
        args: ["--fix"]
        name: "Run ruff linter"

      - id: ruff-format
        name: "Run ruff formatter"

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.1.1
    hooks:
      - id: biome-check
        name: Biome Check (Frontend)
        entry: bash -c 'cd frontend && npx @biomejs/biome@1.9.4 check --write'
        language: system
        files: "frontend/.*\\.(js|ts|vue|json|jsx|tsx)$"
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              frontend/components.d.ts|
              meet/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*|
              meet/templates/includes/.*|
              meet/public/js/lib/.*
          )$

      - id: biome-check
        name: Biome Check (SFU Server)
        entry: bash -c 'cd sfu-server && npm run lint:fix'
        language: system
        files: "sfu-server/.*\\.(js|ts|json)$"
        exclude: |
          (?x)^(
              .*node_modules.*|
              sfu-server/dist/.*
          )$

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
